version: 0.2

phases:
  pre_build:
    commands:
      - gem install cfn-nag
  build:
    commands:
      - echo 'In Build'
      - cfn_nag_scan --input-path service.yaml
      - ./tests/checkaccesskeys.sh